import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const poppinsRegular = localFont({
  src: "./fonts/Poppins-Regular.woff",
  variable: "--font-poppins-regular",
});
const poppinsMedium = localFont({
  src: "./fonts/Poppins-Medium.woff",
  variable: "--font-poppins-medium",
});
const poppinsBold = localFont({
  src: "./fonts/Poppins-Bold.woff",
  variable: "--font-poppins-bold",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppinsRegular.variable} ${poppinsMedium.variable} ${poppinsBold.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
