import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/globals/header";
import Footer from "@/components/globals/footer";
import { ClerkProvider } from "@clerk/nextjs";

const poppins = localFont({
  src: [
    {
      path: "./fonts/Poppins-Bold.woff",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/Poppins-Medium.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Poppins-Regular.woff",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${poppins.variable} antialiased bg-background`}>
          <ThemeProvider attribute={"class"} defaultTheme="dark">
            <Header />
            {children}
            <Footer />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
